[package]
name = "rustrat-client"
version = "0.1.0"
authors = ["Emil Taylor Bye <phptph@gmail.com>"]
edition = "2018"

[dependencies]
wasm3 = "0.1.3"
libffi = "1.0.0"
num-traits = "0.2"
num-derive = "0.3"